version: '3'
services:
  integration:
    image: ${DOCKER_USER}/servers:${BUILD_VERSION}
    hostname: integration
    container_name: integration
    depends_on:
      - servers
    command: dotnet vstest ./Adaptive.ReactiveTrader.Server.IntegrationTests.dll
  e2e:
    image: ${DOCKER_USER}/e2ebase:${BUILD_VERSION}
    hostname: e2e
    container_name: e2e
    command: 'npm run e2e -- --chromeDriver=/usr/bin/chromedriver --baseUrl=http://nginx'
    depends_on:
      - e2ebase
      - client
      - nginx
      - servers
